apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.postgres.POSTGRES_PASSWORD | b64enc | quote  }}
  postgres-db: {{ .Values.postgres.POSTGRES_DB | b64enc | quote }}
  postgres-user: {{ .Values.postgres.POSTGRES_USER | b64enc | quote }}