# my global config
global:
  scrape_interval: 15s  # how frequently to scrape targets
  evaluation_interval: 15s  # how frequently to evaluate rules

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '158.160.34.167:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/alert.rules.yml"

# Scrape configuration
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nodes"
    static_configs:
      - targets:
          - "158.160.34.167:9100"  # srv
          - "158.160.55.15:9100"  # app
          - "158.160.40.254:9100"  # master
